name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit Testing
    services:
      mongo-db:
        image: zakir1386/mongo-db:non-prod
        ports:
          - 27017:27017
    env:
      MONGO_URI: 'mongodb://localhost:27017/superData?authSource=admin'
      MONGO_USERNAME: mongo-admin
      MONGO_PASSWORD: mongo-pass
    strategy:
      matrix:
        node-version: ['18', '20']
        os: [ubuntu-latest]
        exclude:
        - os: macos-latest
          node-version: '18'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up NodeJS Version - ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests
      id: nodejs-tests
      run: npm test

    - name: Archive Test Results
      if: failure() || success()
      uses: actions/upload-artifact@v7
      with:
        name: mocha-test-results
        path: test-results.xml

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up NodeJS Version - 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      run: npm install

    - name: Run Code Coverage
      continue-on-error: true
      run: npm run coverage

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v7
      with:
        name: coverage-report
        path: coverage/lcov-report
        retention-days: 5

  Docker:
    name: Docker Build and Push
    needs: [unit-testing, code-coverage]
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to Docker GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Build
      uses: docker/build-push-action@v5 
      with:
        context: .
        push: false
        tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

    - name: Docker image test
      run: |
        docker images
        docker run --name solar-system-app -d -p 3000:3000 \
          -e MONGO_URI=${{ env.MONGO_URI }} \
          -e MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
          -e MONGO_PASSWORD=${{ env.MONGO_PASSWORD }} \
          ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
        
        export IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
        echo "Docker container IP: $IP"

        echo Testing Image URL using wget
        wget -qO - 127.0.0.1:3000/live | grep live

    - name: Docker Registry Push
      uses: docker/build-push-action@v5 
      with:
        context: .
        push: true
        tags: |
          ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}



        

