name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        node-version: ['18', '19', '20']
        os: [ubuntu-latest, macos-latest]
        exclude:
        - os: macos-latest
          node-version: '18'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up NodeJS Version - 18
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm test

    - name: Archive Test Results
      uses: actions/upload-artifact@v7
      with:
        name: mocha-test-results
        path: test-results.xml

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up NodeJS Version - 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Run Code Coverage
      run: npm run coverage

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v7
      with:
        name: coverage-report
        path: coverage/lcov-report
        retention-days: 5